language: node_js

node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14

script:
  - npm run eslint
  - npm run sasslint
  - npm test
  - npm run build

deploy:
  provider: npm
  email: ain@flashbit.net
  api_key:
    secure: fXOhVeA6CyD6ej16UIgssrKPR+Wo0823wLzdc5ZziJRM2/sw/oxtwRtEo7wQt0nwmeeDOfZ4W3Upg7QP2beDzXZHCvojr7Zy0b4bTxn2paV26SoQ9b0ROO26Mj5h5k8MWx+9/ErHmfhfxXvsueWTIi9aDfsuVQjCkZ9hjgBPLaab/lppyGG8CTjMXPnVDKibzaBHLLpTt9O66Rtx/GX+xnjZRyY0LE4H5J+jslVnp6ZekK7isaTjdohYIu1NytHdpI3p+fiMEWwGa/Q/i3TjPT7U/nsMpVNLZMFYeCwSVA8eRroQ5lBQaMY2Gee2bO0pmKyYK+wt5WbTxyfisxViCOte8PJ39PjVpY+wuuoSHpsq7DM1rjH6kSrMZ1xI/ZPk06+rTQltznC9/a7kftKqGSzHQ3ov5h55flQxMXl4d+ZNunowBTyvdGVpxegk16fiJPlyNDUdtO3l6Y95d77/4xVO/pCNep7JEDNXPnz5ddVorNzPvHghZhQpWi9FPlm1YJXTDXCzdz1TXuFZsVbug7HTKCttkiLcXKP1Lf5NeE1uCU2I+IcJqhPUFWezR35rz3Wx3QEnUQc/RV75htXeoP3fzFYxRen1Hb248JyHA3PlFaPMnEdiensVfluORKWW/RrwTX9qeH916KQbXhcaNqOGBFrPOe6MdUQg+gaUEC0=
  on:
    tags: true
    repo: ain/smartbanner.js
